# Generated by Django 6.0.2 on 2026-03-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_recipe_options_recipe_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
