# Generated by Django 6.0.2 on 2026-03-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_recipe_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
    ]
