# Generated by Django 6.0.2 on 2026-03-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_tagpost_alter_recipe_cat_recipe_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('carbs', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='catalog.nutrition'),
        ),
    ]
